// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdLofNW09NPPnvJBYpqwIFIuMOYI_ZSoM',
    appId: '1:1011746930673:web:497df045a59f3de4c08e50',
    messagingSenderId: '1011746930673',
    projectId: 'omegleclone-47602',
    authDomain: 'omegleclone-47602.firebaseapp.com',
    storageBucket: 'omegleclone-47602.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9d1Jjel4Pts-B8yN-22rFjb0fWxVEY84',
    appId: '1:1011746930673:android:a11c626c6d579c68c08e50',
    messagingSenderId: '1011746930673',
    projectId: 'omegleclone-47602',
    storageBucket: 'omegleclone-47602.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuk_D0BxfaDekAaoYebPeQGRzJACv2An0',
    appId: '1:1011746930673:ios:f6a687459b1ba7acc08e50',
    messagingSenderId: '1011746930673',
    projectId: 'omegleclone-47602',
    storageBucket: 'omegleclone-47602.appspot.com',
    iosBundleId: 'com.example.twitch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuk_D0BxfaDekAaoYebPeQGRzJACv2An0',
    appId: '1:1011746930673:ios:b06385cd615101f2c08e50',
    messagingSenderId: '1011746930673',
    projectId: 'omegleclone-47602',
    storageBucket: 'omegleclone-47602.appspot.com',
    iosBundleId: 'com.example.twitch.RunnerTests',
  );
}
